context("predict")

test_that("Step by step modeling", {
  task = getTask("iris")
  learner = getLearner("classif.dummy", method = "sample")
  model = train(task, learner)
  expect_is(model, "WrappedModel")
  pred = predict(model, task)
  expect_integer(pred$ids, len = 150, any.missing = FALSE)
  expect_character(pred$response, len = 150, any.missing = FALSE)
  expect_subset(pred$response, levels(iris$Species))

  train = sample(150, 100)
  test = setdiff(seq_len(150), train)
  learner = getLearner("classif.rpart", mtry = 2)
  model = train(task, learner, subset = train)
  expect_is(model, "WrappedModel")
  pred = predict(model, task, subset = test)
  expect_integer(pred$ids, len = length(test), any.missing = FALSE)
  expect_character(pred$response, len = length(test), any.missing = FALSE)
  expect_subset(pred$response, levels(iris$Species))
})
